//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A8_WordCount.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Map", ReplyAction="http://tempuri.org/IService1/MapResponse")]
        string[] Map(int N, string[] words);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Map", ReplyAction="http://tempuri.org/IService1/MapResponse")]
        System.Threading.Tasks.Task<string[]> MapAsync(int N, string[] words);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Reduce", ReplyAction="http://tempuri.org/IService1/ReduceResponse")]
        string[] Reduce(string partition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Reduce", ReplyAction="http://tempuri.org/IService1/ReduceResponse")]
        System.Threading.Tasks.Task<string[]> ReduceAsync(string partition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Combiner", ReplyAction="http://tempuri.org/IService1/CombinerResponse")]
        System.Collections.Generic.KeyValuePair<string, int>[] Combiner(string[] reducersArray);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Combiner", ReplyAction="http://tempuri.org/IService1/CombinerResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.KeyValuePair<string, int>[]> CombinerAsync(string[] reducersArray);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : A8_WordCount.ServiceReference.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<A8_WordCount.ServiceReference.IService1>, A8_WordCount.ServiceReference.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] Map(int N, string[] words) {
            return base.Channel.Map(N, words);
        }
        
        public System.Threading.Tasks.Task<string[]> MapAsync(int N, string[] words) {
            return base.Channel.MapAsync(N, words);
        }
        
        public string[] Reduce(string partition) {
            return base.Channel.Reduce(partition);
        }
        
        public System.Threading.Tasks.Task<string[]> ReduceAsync(string partition) {
            return base.Channel.ReduceAsync(partition);
        }
        
        public System.Collections.Generic.KeyValuePair<string, int>[] Combiner(string[] reducersArray) {
            return base.Channel.Combiner(reducersArray);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.KeyValuePair<string, int>[]> CombinerAsync(string[] reducersArray) {
            return base.Channel.CombinerAsync(reducersArray);
        }
    }
}
